# Exercice XP

👩‍🏫 👩🏿‍🏫 What You Will Learn
Fundamental concepts and the significance of data analysis in modern contexts
Identification and classification of different data types, including qualitative vs. quantitative data
Understanding structured and unstructured data, with techniques for converting unstructured data into structured formats
Application of basic data analysis techniques using Python, Pandas, Matplotlib, and Seaborn
Practical use of Jupyter Notebook and Google Colab for data analysis workflows
Methods for importing datasets from multiple sources, including CSV files, JSON data from URLs, and Kaggle datasets
Displaying, inspecting, and validating datasets using Pandas
Applying data types effectively in analytical and business contexts


🛠️ What You Will Create
Data Analysis Essay / Report (Exercise 1)
A written report defining data analysis, explaining its importance, and discussing real-world applications.

Data Type Classification Report (Exercise 2)
An in-depth analysis of the Iris dataset, classifying each feature as qualitative or quantitative with clear justifications.

Data Analysis Notebook (Exercise 3)
A comprehensive Jupyter Notebook demonstrating:

Statistical calculations (mean, median, mode)

Data visualizations (histograms, bar charts)
Clear documentation and interpretation of results

Data Import & Structuring Scripts

Import and explore the Titanic dataset directly from Kaggle

Import the Iris dataset from a CSV file and display initial records
Fetch and read JSON data from a URL using Pandas
Convert raw and unstructured data into structured, analysis-ready formats

In [45]:
import pandas as pd
import numpy as np
import zipfile
import requests
from io import BytesIO

## Exercie 1 : Introduction to Data Analysis (Easy)

Objective: Understand the basic overview and significance of data analysis.
Task:
Write a short essay or report on the following topics:

What is data analysis?
Why is data analysis important in modern contexts?
List and describe three areas where data analysis is applied today.
Hint/Tip:

Research current trends in data analysis and real-world examples to provide depth to your essay.

What is Data Analysis?

Data analysis is the systematic process of inspecting, cleaning, transforming, and modeling data to discover useful information, draw conclusions, and support decision-making. It involves applying statistical and computational techniques to extract meaningful patterns, trends, and insights from raw data. The process typically includes data collection, preprocessing, exploratory analysis, statistical modeling, and interpretation of results.

Modern data analysis encompasses various methodologies, from descriptive statistics that summarize historical data to predictive analytics that forecast future trends, and prescriptive analytics that recommend optimal actions.

Why is Data Analysis Important in Modern Contexts?

Data analysis has become crucial in today's world for several compelling reasons:

**1. Data Explosion**: We generate approximately 2.5 quintillion bytes of data daily. Without proper analysis, this vast information remains meaningless noise rather than actionable intelligence.

**2. Competitive Advantage**: Organizations that effectively analyze data can identify market opportunities, optimize operations, and respond faster to changing conditions than their competitors.

**3. Evidence-Based Decision Making**: Data analysis replaces intuition-based decisions with fact-driven strategies, reducing risks and improving outcomes across all sectors.

**4. Efficiency and Cost Reduction**: By identifying inefficiencies and optimization opportunities, data analysis helps organizations streamline processes and reduce operational costs.

**5. Personalization and Customer Experience**: Analysis of customer behavior enables personalized services, improving satisfaction and loyalty.

Three Key Application Areas of Data Analysis

1. Healthcare and Medical Research

Data analysis revolutionizes healthcare through:
- **Electronic Health Records (EHR) Analysis**: Identifying treatment patterns and patient outcomes
- **Drug Discovery**: Analyzing molecular data to accelerate pharmaceutical development
- **Epidemiological Studies**: Tracking disease spread and effectiveness of public health interventions
- **Personalized Medicine**: Using genetic and lifestyle data to tailor treatments

*Real-world example*: During COVID-19, data analysis enabled real-time tracking of infection rates, vaccine effectiveness monitoring, and resource allocation optimization across healthcare systems globally.

2. Financial Services and Fintech

The financial sector leverages data analysis for:
- **Risk Assessment**: Evaluating creditworthiness and investment risks using historical and behavioral data
- **Fraud Detection**: Identifying suspicious transactions through pattern recognition and anomaly detection
- **Algorithmic Trading**: Using market data analysis for automated trading decisions
- **Regulatory Compliance**: Monitoring transactions for anti-money laundering and compliance requirements

*Real-world example*: Credit card companies analyze millions of transactions in real-time to detect fraudulent activities, preventing billions in losses annually while minimizing false positives that inconvenience customers.

3. E-commerce and Digital Marketing

Online businesses utilize data analysis for:
- **Customer Segmentation**: Grouping customers based on behavior, preferences, and demographics
- **Recommendation Systems**: Suggesting products based on purchase history and browsing patterns
- **Price Optimization**: Dynamic pricing based on demand, competition, and customer willingness to pay
- **Supply Chain Management**: Optimizing inventory levels and logistics based on demand forecasting

*Real-world example*: Amazon's recommendation engine, powered by collaborative filtering and machine learning algorithms, drives approximately 35% of their revenue by analyzing customer behavior patterns and purchase histories.

Current Trends and Future Outlook

Modern data analysis is evolving rapidly with trends including:
- **Real-time Analytics**: Processing streaming data for immediate insights
- **Artificial Intelligence Integration**: Combining traditional statistics with machine learning
- **Automated Analytics**: Self-service platforms enabling non-technical users to perform analysis
- **Edge Analytics**: Processing data closer to its source for faster decision-making

## Exercice 2 : Dataset Loading and Initial Analysis

Objective: Practice dataset loading from Kaggle and initial analysis.
Task:
for the following dataset : How Much Sleep Do Americans Really Get?, Global Trends in Mental Health Disorder and Credit Card Approvals.

Load the dataset into Jupyter or Google Colab.
Display the first few rows.
Provide a brief dataset description.

### Load dataset

In [18]:
path = "./Data/Time Americans Spend Sleeping.csv"

In [19]:
df = pd.read_csv(path)

### Display the first few rows

In [20]:
df.head()

,index,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
0,0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both

### Description

In [21]:
df.describe()

            index         Year  Avg hrs per day sleeping  Standard Error
count  945.000000   945.000000                945.000000      945.000000
mean   472.000000  2010.000000                  8.806868        0.086958
std    272.942302     4.322782                  0.545001        0.034631
min      0.000000  2003.000000                  7.720000        0.018000
25%    236.000000  2006.000000                  8.360000        0.063000
50%    472.000000  2010.000000                  8.810000        0.084000
75%    708.000000  2014.000000                  9.190000        0.106000
max    944.000000  2017.000000                 10.650000        0.228000

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 945 entries, 0 to 944
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   index                     945 non-null    int64
 1   Year                      945 non-null    int64
 2   Period                    945 non-null    object
 3   Avg hrs per day sleeping  945 non-null    float64
 4   Standard Error            945 non-null    float64
 5   Type of Days              945 non-null    object
 6   Age Group                 945 non-null    object
 7   Activity                  945 non-null    object
 8   Sex                       945 non-null    object
dtypes: float64(2), int64(2), object(5)
memory usage: 66.6+ KB

## Exercise 3: Identifying Data Types

Objective: Learn to identify different data types.
Task:
For the datasets from the previous exercise, categorize each column of it as either quantitative or qualitative and explain your reasoning.

In [23]:
df = df.drop(columns=["index"])

In [24]:
df.head()

,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both

In [25]:
columns_analysis = {
    
    'Year': {
        'type': 'Quantitative - Discrete (Temporal)',
        'reasoning': 'Numeric values representing specific years; discrete time points with meaningful order'
    },
    'Period': {
        'type': 'Qualitative - Categorical',
        'reasoning': 'Text describing time period type; represents categories of measurement periods'
    },
    'Avg hrs per day sleeping': {
        'type': 'Quantitative - Continuous',
        'reasoning': 'Decimal numbers representing measurable quantities; can take any value within a reasonable range'
    },
    'Standard Error': {
        'type': 'Quantitative - Continuous',
        'reasoning': 'Decimal numbers representing statistical measure of precision; continuous measurement values'
    },
    'Type of Days': {
        'type': 'Qualitative - Categorical',
        'reasoning': 'Text describing categories of days being measured; represents distinct groups'
    },
    'Age Group': {
        'type': 'Qualitative - Ordinal',
        'reasoning': 'Text representing age categories; has implicit ordering (younger to older ages)'
    },
    'Activity': {
        'type': 'Qualitative - Categorical',
        'reasoning': 'Text describing the type of activity being measured; represents distinct categories'
    },
    'Sex': {
        'type': 'Qualitative - Categorical',
        'reasoning': 'Text representing gender categories; distinct groups for demographic classification'
    }
}

In [27]:
df_types = pd.DataFrame(df)

# Analyze each column
print("DATA TYPE CATEGORIZATION")

print("-" * 70)

# Display detailed analysis
for column, analysis in columns_analysis.items():
    print(f"\nColumn: '{column}'")
    print(f"Type: {analysis['type']}")
    print(f"Reasoning: {analysis['reasoning']}")
    print(f"Sample values: {df[column].unique()[:3]}")
    print(f"Data type in pandas: {df[column].dtype}")

DATA TYPE CATEGORIZATION
----------------------------------------------------------------------

Column: 'Year'
Type: Quantitative - Discrete (Temporal)
Reasoning: Numeric values representing specific years; discrete time points with meaningful order
Sample values: [2003 2004 2005]
Data type in pandas: int64

Column: 'Period'
Type: Qualitative - Categorical
Reasoning: Text describing time period type; represents categories of measurement periods
Sample values: ['Annual']
Data type in pandas: object

Column: 'Avg hrs per day sleeping'
Type: Quantitative - Continuous
Reasoning: Decimal numbers representing measurable quantities; can take any value within a reasonable range
Sample values: [8.57 8.55 8.62]
Data type in pandas: float64

Column: 'Standard Error'
Type: Quantitative - Continuous
Reasoning: Decimal numbers representing statistical measure of precision; continuous measurement values
Sample values: [0.018 0.026 0.023]
Data type in pandas: float64

Column: 'Type of Days'
Type: Qualitative - Categorical
Reasoning: Text describing categories of days being measured; represents distinct groups
Sample values: ['All days' 'Nonholiday weekdays' 'Weekend days and holidays']
Data type in pandas: object

Column: 'Age Group'
Type: Qualitative - Ordinal
Reasoning: Text representing age categories; has implicit ordering (younger to older ages)
Sample values: ['15 years and over' '15 to 24 years' '25 to 34 years']
Data type in pandas: object

Column: 'Activity'
Type: Qualitative - Categorical
Reasoning: Text describing the type of activity being measured; represents distinct categories
Sample values: ['Sleeping']
Data type in pandas: object

Column: 'Sex'
Type: Qualitative - Categorical
Reasoning: Text representing gender categories; distinct groups for demographic classification
Sample values: ['Both' 'Men' 'Women']
Data type in pandas: object

## Exercise 4: Exploring Data Types

Objective: Learn about different types of data in data analysis.
Task:
Load the Iris dataset using Kaggle into a Jupyter Notebook or Google Colaboratory Notebook.
Identify and list which columns in your dataset are qualitative and which are quantitative.
Write a brief description of why each column is classified as qualitative or quantitative.
Tools: Jupyter Notebook, Python with Pandas library.

In [28]:
path_ex4 = "./Data/Iris.csv"

In [31]:
df_ex4 = pd.read_csv(path_ex4)
df_ex4.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [34]:
df_ex4 = df_ex4.drop(columns = ["Id"])

In [36]:
df_ex4.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [37]:
# Identify quantitative and qualitative columns programmatically
quantitative_columns = df.select_dtypes(include=[np.number]).columns.tolist()
qualitative_columns = df.select_dtypes(include=['object', 'category']).columns.tolist()

print("Column Classification:")
print("-" * 70)
print(f"Quantitative Columns: {quantitative_columns}")
print(f"Qualitative Columns: {qualitative_columns}")

Column Classification:
----------------------------------------------------------------------
Quantitative Columns: ['Year', 'Avg hrs per day sleeping', 'Standard Error']
Qualitative Columns: ['Period', 'Type of Days', 'Age Group', 'Activity', 'Sex']

In [38]:
# Detailed analysis of each column
print("Detailed Column Analysis:")
print("-" * 70)
for column in df.columns:
    if column in quantitative_columns:
        print(f"{column}: Quantitative (Continuous)")
        print(f"  - Range: {df[column].min():.2f} to {df[column].max():.2f}")
        print(f"  - Mean: {df[column].mean():.2f}")
    else:
        print(f"{column}: Qualitative (Categorical)")
        print(f"  - Unique values: {df[column].unique()}")
        print(f"  - Number of categories: {df[column].nunique()}")
    print()

Detailed Column Analysis:
----------------------------------------------------------------------
Year: Quantitative (Continuous)
  - Range: 2003.00 to 2017.00
  - Mean: 2010.00

Period: Qualitative (Categorical)
  - Unique values: ['Annual']
  - Number of categories: 1

Avg hrs per day sleeping: Quantitative (Continuous)
  - Range: 7.72 to 10.65
  - Mean: 8.81

Standard Error: Quantitative (Continuous)
  - Range: 0.02 to 0.23
  - Mean: 0.09

Type of Days: Qualitative (Categorical)
  - Unique values: ['All days' 'Nonholiday weekdays' 'Weekend days and holidays']
  - Number of categories: 3

Age Group: Qualitative (Categorical)
  - Unique values: ['15 years and over' '15 to 24 years' '25 to 34 years' '35 to 44 years'
 '45 to 54 years' '55 to 64 years' '65 years and over']
  - Number of categories: 7

Activity: Qualitative (Categorical)
  - Unique values: ['Sleeping']
  - Number of categories: 1

Sex: Qualitative (Categorical)
  - Unique values: ['Both' 'Men' 'Women']
  - Number of categories: 3

## Exercise 5: Basic Observation Skills in Data Analysis

Objective: Develop observation skills for data analysis.
Task:
Load the How Much Sleep Do Americans Really Get? dataset into Jupyter or Google Colab.
Identify columns that could be interesting for a specific type of analysis (e.g., trend analysis, group comparison) and explain your choice.
Tools: Jupyter Notebook, Python with Pandas library.

In [39]:
path5 = "./Data/Time Americans Spend Sleeping.csv"

In [42]:
df_ex5 = pd.read_csv(path5)
df_ex5.head()

,index,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
0,0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both

In [49]:
df_ex5 = df_ex5.drop(columns = ["index"]).head()

### UNIQUE VALUES ANALYSIS

In [50]:
# Explore unique values in categorical columns
categorical_cols = ['Year', 'Period', 'Type of Days', 'Age Group', 'Activity', 'Sex']
for col in categorical_cols:
    if col in df.columns:
        unique_vals = df[col].unique()
        print(f"\n{col} ({len(unique_vals)} unique values):")
        print(unique_vals)

Year (15 unique values):
[2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016
 2017]

Period (1 unique values):
['Annual']

Type of Days (3 unique values):
['All days' 'Nonholiday weekdays' 'Weekend days and holidays']

Age Group (7 unique values):
['15 years and over' '15 to 24 years' '25 to 34 years' '35 to 44 years'
 '45 to 54 years' '55 to 64 years' '65 years and over']

Activity (1 unique values):
['Sleeping']

Sex (3 unique values):
['Both' 'Men' 'Women']

### STATISTICAL SUMMARY

In [51]:
# Statistical summary of numerical columns
df_ex5.describe()

              Year  Avg hrs per day sleeping  Standard Error
count     5.000000                  5.000000           5.000
mean   2005.000000                  8.588000           0.023
std       1.581139                  0.034928           0.003
min    2003.000000                  8.550000           0.018
25%    2004.000000                  8.570000           0.023
50%    2005.000000                  8.570000           0.024
75%    2006.000000                  8.620000           0.024
max    2007.000000                  8.630000           0.026

### MISSING VALUES

In [52]:
# Check for missing values
df_ex5.isnull().sum()

Year                        0
Period                      0
Avg hrs per day sleeping    0
Standard Error              0
Type of Days                0
Age Group                   0
Activity                    0
Sex                         0
dtype: int64

## Exercise 6: Identifying Data Types

Below are various data sources. Identify whether each one is an example of structured or unstructured data.

A company’s financial reports stored in an Excel file.
Photographs uploaded to a social media platform.
A collection of news articles on a website.
Inventory data in a relational database.
Recorded interviews from a market research study.

**A company's financial reports stored in an Excel file: STRUCTURED**
- Excel files contain data organized in rows and columns with defined headers
- Financial reports follow standardized formats with specific fields (revenue, expenses, dates, etc.)
- Data can be easily queried, sorted, and analyzed using spreadsheet functions

**Photographs uploaded to a social media platform: UNSTRUCTURED**
- Images are binary files without inherent tabular organization
- Content varies widely and doesn't follow a predefined schema
- Requires specialized processing (computer vision, image recognition) to extract meaningful information

**A collection of news articles on a website: UNSTRUCTURED**
- Text content varies in length, style, and format
- No standardized fields or consistent structure across articles
- Requires natural language processing techniques to analyze and extract insights

**Inventory data in a relational database: STRUCTURED**
- Stored in tables with defined schemas, columns, and data types
- Follows relational database principles with primary keys, foreign keys, and relationships
- Can be easily queried using SQL and follows ACID properties

**Recorded interviews from a market research study: UNSTRUCTURED**
- Audio files contain natural speech with varying topics and responses
- No predefined format or consistent structure
- Requires transcription and natural language processing for analysis

## Exercise 7: Transformation Exercise

For each of the following unstructured data sources, propose a method to convert it into structured data. Explain your reasoning.

A series of blog posts about travel experiences.
Audio recordings of customer service calls.
Handwritten notes from a brainstorming session.
A video tutorial on cooking.

1. Series of Blog Posts About Travel Experiences

**Method**: Natural Language Processing (NLP) with text extraction and categorization

**Approach**:
- Extract metadata (date, author, location, title)
- Use named entity recognition (NER) to identify places, dates, activities
- Sentiment analysis to gauge experience quality
- Topic modeling to categorize content themes
- Extract structured fields like destinations, duration, budget mentions, activities

**Reasoning**: Blog posts contain rich textual information that can be parsed using NLP techniques. The semi-structured nature (titles, dates, paragraphs) provides natural breakpoints for extraction.

**Suggested Python packages**: `spacy`, `nltk`, `pandas`, `beautifulsoup4`, `textblob`, `gensim`

2. Audio Recordings of Customer Service Calls

**Method**: Speech-to-text conversion followed by conversation analysis

**Approach**:
- Convert audio to text using speech recognition
- Identify speakers and segment conversations
- Extract call metadata (duration, timestamp, caller ID)
- Analyze sentiment and emotion throughout the call
- Categorize issues/topics discussed
- Extract resolution status and satisfaction indicators

**Reasoning**: Audio data requires transcription first, then similar NLP techniques as text. The conversational nature allows for dialogue analysis and customer journey mapping.

**Suggested Python packages**: `speech_recognition`, `pydub`, `whisper`, `spacy`, `transformers`, `librosa`

3. Handwritten Notes from Brainstorming Session

**Method**: Optical Character Recognition (OCR) combined with document structure analysis

**Approach**:
- Use OCR to convert handwritten text to digital text
- Identify different handwriting styles (multiple participants)
- Extract ideas, action items, and decisions
- Categorize content by themes or topics
- Create relationships between connected ideas
- Extract timestamps if available

**Reasoning**: Handwritten notes require image processing first. The challenge lies in accuracy of handwriting recognition and interpreting the non-linear nature of brainstorming notes.

**Suggested Python packages**: `pytesseract`, `opencv-python`, `pillow`, `easyocr`, `pandas`, `networkx`

4. Video Tutorial on Cooking

**Method**: Multi-modal analysis combining video, audio, and visual processing

**Approach**:
- Extract audio track and convert to text (instructions)
- Perform object detection to identify ingredients and tools
- Segment video into cooking steps/phases
- Extract timing information for each step
- Identify cooking techniques through action recognition
- Create ingredient lists and equipment requirements

**Reasoning**: Cooking videos contain multiple data streams (visual, audio, temporal) that need coordinated analysis. The structured nature of recipes makes this suitable for step-by-step extraction.

**Suggested Python packages**: `opencv-python`, `moviepy`, `speech_recognition`, `tensorflow`, `torch`, `ultralytics` (YOLO), `whisper`

## Exercise 8 : Import a file from Kaggle

Note: This dataset was originally sourced from Kaggle, but for easier access, it has been made available on GitHub.

👉 Please download the dataset directly from the GitHub repository to use it in this project.

Import the train dataset. Use the train.csv file.
Print the first few rows of the DataFrame.

In [53]:
path8 = "./Data/train.csv"

In [54]:
df_ex8 = pd.read_csv(path8)
df_ex8.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

 ## Exercise 9 : Export a dataframe to excel format and JSON format.

Create a simple dataframe.
Export the dataframe to an excel file.
Export the dataframe to a JSON file.

In [56]:
# Step 1: Create a simple DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'London', 'Tokyo', 'Paris'],
    'Salary': [50000, 60000, 70000, 55000]
}

df_ex9 = pd.DataFrame(data)
df_ex9.head()

      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30    London   60000
2  Charlie   35     Tokyo   70000
3    Diana   28     Paris   55000

### Export to Excel file

In [60]:
# Step 2: Export to Excel file
df.to_excel('./Data/output/sample_data.xlsx', index=False)

### Export to JSON file

In [61]:
# Step 3: Export to JSON file
df.to_json('./Data/output/sample_data.json', orient='records', indent=2)

## Exercise 10: Reading JSON Data

Use a sample JSON dataset

Import the JSON data from the provided URL.
Use Pandas to read the JSON data.
Display the first five entries of the data.

In [62]:
path10 = "./Data/posts.json"

In [64]:
df_ex10 = pd.read_json(path10)
df_ex10

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...
...,...,...,...,...
95,10,96,quaerat velit veniam amet cupiditate aut numqu...,in non odio excepturi sint eum\nlabore volupta...
96,10,97,quas fugiat ut perspiciatis vero provident,eum non blanditiis soluta porro quibusdam volu...
97,10,98,laboriosam dolor voluptates,doloremque ex facilis sit sint culpa\nsoluta a...
98,10,99,temporibus sit alias delectus eligendi possimu...,quo deleniti praesentium dicta non quod\naut e...
99,10,100,at nam consequatur ea labore ea harum,cupiditate quo est a modi nesciunt soluta\nips...